src/schemas/ClusterRoutingTableRequest.yaml

Just change "result" property name to "routes"

change request name for routing table

---

src/openapi.yaml
src/resources/AccountGitRepositoryBitbucket.yaml
src/resources/AccountGitRepositoryBitbucketBranch.yaml

Adding following endpoints: 
- /account/bitbucket/repository
- /account/bitbucket/repository/branch

Adding endpoints for Bitbutcket repositories support

---

src/schemas/ApplicationEditRequest.yaml
src/schemas/ApplicationRequest.yaml
src/schemas/ApplicationResponse.yaml

Add buildpack-language parameter

Add buildpack-langage parameter for app install

---

src/openapi.yaml
src/resources/ApplicationNetwork.yaml
src/schemas/ApplicationNetworkRequest.yaml
src/schemas/ApplicationNetworkResponse.yaml
src/schemas/ApplicationRequest.yaml
src/schemas/ApplicationResponse.yaml
src/schemas/_index.yaml

- Delete sticky parameter in Application endpoint
- Add a specific endpoint for Network settings
- Add an "Application configuration" category

Delete sticky param from app & add specific endpoint

---

src/schemas/Status.yaml

Add deployment{up-to-date} parameter in :ApplicationId and :ServiceId endpoints.

Add uptodate parameter for services

---

src/schemas/EnvironmentVariableResponse.yaml

Add service name on Environment variables

Add service_name param on env vars

---

src/schemas/EnvironmentVariableAlias.yaml
src/schemas/EnvironmentVariableOverride.yaml
src/schemas/SecretAlias.yaml
src/schemas/SecretOverride.yaml

Expose `mount_path` and `type` to aliased + overriden vars to aliased
and overridden variables.

feat: expose mount path and var type

---

src/openapi.yaml
src/parameters/_index.yaml
src/parameters/path/databaseType.yaml
src/resources/CloudProviderAWSManagedDatabaseInstanceType.yaml
src/resources/CloudProviderAWSManagedDatabaseType.yaml
src/resources/CloudProviderDOManagedDatabaseInstanceType.yaml
src/resources/CloudProviderDOManagedDatabaseType.yaml
src/resources/CloudProviderSCWManagedDatabaseInstanceType.yaml
src/resources/CloudProviderSCWManagedDatabaseType.yaml
src/schemas/DatabaseRequest.yaml
src/schemas/DatabaseResponse.yaml
src/schemas/ManagedDatabaseInstanceTypeResponse.yaml
src/schemas/ManagedDatabaseInstanceTypeResponseList.yaml
src/schemas/ManagedDatabaseTypeResponse.yaml
src/schemas/ManagedDatabaseTypeResponseList.yaml
src/schemas/_index.yaml

- feat: add instance type field to DB
- feat: add database type endpoint
- feat: add database instance type endpoint

feat: add database instance type support

---

src/schemas/DatabaseEditRequest.yaml

feat: add missing db instance type to edit

---

src/schemas/ApplicationDeploymentRestrictionResponseList.yaml

fix(deployment-restrictions): fix list schema

---

src/schemas/EnvironmentStatus.yaml
src/schemas/Stage.yaml
src/schemas/Status.yaml

total_deployment_duration_in_seconds in environment status

chore: rename metrics to steps in status and  add total deployment duration

---

src/openapi.yaml
src/resources/CloudProviderGcpClusterFeature.yaml
src/resources/CloudProviderGcpCredentials.yaml
src/resources/CloudProviderGcpCredentialsRef.yaml
src/resources/CloudProviderGcpGkeInstanceType.yaml
src/resources/CloudProviderGcpManagedDatabaseType.yaml
src/resources/CloudProviderGcpRegion.yaml
src/schemas/GcpCredentialsRequest.yaml
src/schemas/_index.yaml
src/schemas/enums/CloudProvider.yaml

feat: GCP integration new endpoints

---

src/schemas/GcpCredentialsRequest.yaml

chore: update GCP credentials field name

---

src/openapi.yaml
src/resources/OrganizationBillingExternalId.yaml
src/schemas/BillingExternalId.yaml
src/schemas/_index.yaml

Hi team, here is a new endpoint to get access to the Billing External ID from an organization.

feat(COR-1660): Add resource GET `/organization/:id/billingExternalId`

---

src/schemas/ApplicationEditRequest.yaml
src/schemas/ApplicationResponse.yaml

None of the other service types have those attributes as nullable. This cause issues in fronted types between request and response.
https://github.com/Qovery/qovery-openapi-spec/blob/6b50ad4f66a9c215dabba080f1858b42a85a07b5/src/schemas/job/BaseJobResponse.yaml#L31
https://github.com/Qovery/qovery-openapi-spec/blob/6b50ad4f66a9c215dabba080f1858b42a85a07b5/src/schemas/helm/HelmResponse.yaml#L19

fix(schemas): remove nullable attrs

---

src/schemas/ClusterFeatureGcpExistingVpc.yaml
src/schemas/ClusterFeatureResponse.yaml
src/schemas/ClusterRequest.yaml
src/schemas/_index.yaml

feat: add GCP custom VPC support

---

openapi.yaml

add associatedItemsCount when listing annotationsGroup of an organization (and CRON & JOB item type)

---

openapi.yaml

Fix container registry response type

---

openapi.yaml

https://qovery.atlassian.net/browse/COR-720

fix: add missing icon_uri properties

---

openapi.yaml

fix: container registry and helm repository service associated tags

---

openapi.yaml

Add endpoint allowing to upgrade clusters to next available kubernetes versions.

feat(ENG-1807): allow users to upgrade cluster versions

---

openapi.yaml

Introduce by https://github.com/Qovery/qovery-openapi-spec/pull/700

fix: add missing tag

---

openapi.yaml

https://qovery.slack.com/archives/C038JMN9GUE/p1730110620313179?thread_ts=1730102007.488229&cid=C038JMN9GUE

fix(variable-edit-request): add missing enable_interpolation_in_file field

---

openapi.yaml

This reverts commit 9d910e4c565d98b44e4522c89402fa7693212681.

Revert "feat(cor-1138) Set Karpenter qovery node pools mandatory (#746)"

---

openapi.yaml

This PR adds a new API endpoint listing the credentials of a given organization and their associated clusters.

feat(credentials): add organization/{organizationId}/credentials endpoint

---

openapi.yaml

This PR adds a missing tag for the new credentials API endpoint. It also extracts the response to a model.

impr: correct tag and add model for new credentials endpoint
